# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_regis', '0002_auto_20170627_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traded_pokes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes', to='log_regis.Users')),
            ],
        ),
    ]
