# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traded_pokes',
            name='poker',
        ),
        migrations.DeleteModel(
            name='Traded_pokes',
        ),
    ]
